/*
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available
 * under the terms of the MIT license which is available at
 * https://opensource.org/licenses/MIT.
 *
 * SPDX-License-Identifier: MIT
 */

// Some portions generated by Claude Code (Opus 5)

#ifndef BOARD_CONFIG_H
#define BOARD_CONFIG_H

/* CPU Subsystem Frequencies */
#define BSP_CPU_CLOCK_HZ        600000000ULL /* 600 MHz U54 Application Core Clock */
#define BSP_SYSTEM_CLOCK_HZ     BSP_CPU_CLOCK_HZ
#define BSP_CLINT_RTC_FREQ_HZ   1000000ULL   /* 1 MHz Real-Time CLINT Clock in Renode */

/* ThreadX system tick rate. Must match TX_TIMER_TICKS_PER_SECOND; main.c
 * enforces that with a compile-time check. */
#define BSP_TICK_RATE_HZ        100ULL

#define BSP_UART_BAUDRATE       115200
#define BSP_RAM_END             0xC0000000ULL /* 1 GiB LPDDR4 DRAM End Address */

#define BSP_HAS_LED             1
#define BSP_HAS_CONSOLE         1

#endif /* BOARD_CONFIG_H */
